version: '3.7'
services:
  #container de l'application

  application:
    image: python:3.9
    restart: always
    volumes:
      - ${BASE_PATH}/backend/:/fastapi
      - ${BASE_PATH}/images/python/start.sh:start.sh
      - ${BASE_PATH}/backend/requirement:start.sh
    entrypoint: [ 'sh','start.sh' ]
    networks:
      - network
    ports:
      - "${APP_HTTP_PORT}:80"
  #    le service phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - network
    links:
      - mariadb
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PMA_HTTP_PORT}:80"
  #  le service mariadb
  mariadb:
    image: mariadb
    restart: always
    networks:
      - network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${BASE_PATH}/bdd/mariadb/databases:/var/lib/mysql
      - ${BASE_PATH}/bdd/mariadb/my.cnf:/etc/mysql/conf.d/custom.cnf
    labels:
      - "traefik.enable=false"
#    le service de base de donnees redis
  redis:
    image: redis:latest
    restart: always
    networks:
      - network
    labels:
      - "traefik.enable=false"
#    le service de base de donnees redis
  redis-gui:
    image: redislabs/redisinsight:latest
    restart: always
    networks:
      - network
    ports:
      - "${REDIS_GUI_PORT}:8001"


networks:
  network:
    driver: bridge

