<?php

namespace Database\Seeders;

use App\Models\Nation;
use Illuminate\Database\Seeder;

class NationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $liste_pays = [
            "Algérie",
            "Égypte",
            "Libye",
            "Maroc",
            "Sahara occidental",
            "Soudan",
            "Tunisie",
            "Bénin",
            "Burkina Faso",
            "Cap-Vert",
            "Côte d'Ivoire",
            "Gambie",
            "Ghana",
            "Guinée",
            "Guinée-Bissau",
            "Liberia",
            "Mali",
            "Mauritanie",
            "Niger",
            "Nigeria",
            "Sénégal",
            "Sierra Leone",
            "Togo",
            "Burundi",
            "Comores",
            "Djibouti",
            "Érythrée",
            "Éthiopie",
            "Kenya",
            "Madagascar",
            "Malawi",
            "Maurice",
            "Mayotte",
            "Mozambique",
            "Ouganda",
            "Réunion",
            "Rwanda",
            "Seychelles",
            "Somalie",
            "Tanzanie",
            "Zambie",
            "Zimbabwe",
            "Angola",
            "Cameroun",
            "Centrafricaine (République)",
            "Congo",
            "Congo (Rép. dém. du)",
            "Gabon",
            "Guinée équatoriale",
            "Sao Tomé-et-Principe",
            "Tchad",
            "Afrique du Sud",
            "Botswana",
            "Lesotho",
            "Namibie",
            "Swazilan",
            "Canada",
            "États-Unis",
            "Belize",
            "Costa Rica",
            "Guatemala",
            "Honduras",
            "Mexique",
            "Nicaragua",
            "Panama",
            "Salvador",
            "Antigua-et-Barbuda",
            "Aruba",
            "Bahamas",
            "Barbade",
            "Caïmans (îles)",
            "Cuba",
            "Curaçao",
            "Dominicaine (République)",
            "Dominique",
            "Grenade",
            "Guadeloupe",
            "Haïti",
            "Jamaïque",
            "Martinique",
            "Porto Rico",
            "Sainte Lucie",
            "St Vincent-et-les-Grenadines",
            "St. Kitts-et-Nevis",
            "Trinité-et-Tobago",
            "Vierges (Îles)",
            "Argentine",
            "Bolivie",
            "Brésil",
            "Chili",
            "Colombie",
            "Équateur",
            "Guyana",
            "Guyane (française)",
            "Paraguay",
            "Pérou",
            "Surinam",
            "Uruguay",
            "Venezuela",
            "Arabie saoudite",
            "Arménie",
            "Azerbaïdjan",
            "Bahreïn",
            "Chypre",
            "Émirats arabes unis",
            "Georgie",
            "Irak",
            "Israël",
            "Jordanie",
            "Koweït",
            "Liban",
            "Oman",
            "Palestine (Territoires)",
            "Qatar",
            "Syrie",
            "Turquie",
            "Yémen",
            "Afghanistan",
            "Bangladesh",
            "Bhoutan",
            "Inde",
            "Iran",
            "Kazakhstan",
            "Kirghizistan",
            "Maldives",
            "Népa",
            "Ouzbékistan",
            "Pakistan",
            "Sri Lanka",
            "Tadjikistan",
            "Turkménistan",
            "Brunei",
            "Cambodge",
            "Indonésie",
            "Laos",
            "Malaisie",
            "Myanmar (Birmanie)",
            "Philippines",
            "Singapour",
            "Thaïlande",
            "Timor-Est",
            "Viêt Nam",
            "Chine",
            "Chine - Hong Kong",
            "Chine - Macao",
            "Corée du Nord",
            "Corée du Sud",
            "Japon",
            "Mongolie",
            "Taïwan",
            "Danemark",
            "Estonie",
            "Finlande",
            "Irlande",
            "Islande",
            "Lettonie",
            "Lituanie",
            "Norvège",
            "Royaume-Uni",
            "Suède",
            "Allemagne",
            "Autriche",
            "Belgique",
            "France (métropolitaine)",
            "Liechtenstein",
            "Luxembourg",
            "Monaco",
            "Pays-Bas",
            "Suisse",
            "Biélorussie",
            "Bulgarie",
            "Hongrie",
            "Moldavie",
            "Pologne",
            "Roumanie",
            "Russie",
            "Slovaquie",
            "Tchèque (République)",
            "Ukraine",
            "Albanie",
            "Andorre",
            "Bosnie-Herzégovine",
            "Croatie",
            "Espagne",
            "Grèce",
            "Italie",
            "Kosovo",
            "Macédoine",
            "Malte",
            "Monténégro",
            "Portugal",
            "Saint-Marin",
            "Serbie",
            "Slovénie",
            "Australie",
            "Fidji",
            "Guam",
            "Marshall (Îles)",
            "Micronésie (États fédérés de) ",
            "Nouvelle-Calédonie",
            "Nouvelle-Zélande",
            "Palau",
            "Papouasie-Nouvelle-Guinée .",
            "Polynésie française",
            "Salomon (Îles) ",
            "Samoa occidentales",
            "Tonga",
            "Vanuatu",
        ];

        foreach ($liste_pays as $pays) {
            Nation::create([
                'libelle' => $pays,
            ]);
        }
    }
}
