<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'admin-gtech',
                'email' => 'ferrandon@gabontech.com',
                'phone_number' => NULL,
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-12 20:24:59',
                'password' => '$2y$10$G/GOCiRXo2PM30l9e7Lb5.skDYRuHkJx7IhQGFSu9N/iSV9H5nNm6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-11-11 08:36:38',
                'updated_at' => '2021-12-30 10:26:15',
            ),
            1 => 
            array (
                'id' => 3,
                'name' => 'lipot-nyaye-elisee-boris',
                'email' => 'b.lipot@sgs-gabon.com',
                'phone_number' => '',
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2023-02-03 11:23:03',
                'password' => '$2y$10$WMbM.WY/lwliy3mNRsOXAuaY.MsfP9PK/bNQOTdzR9kak6jfzS8a6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'qJc92bWrHbXjQz2gaFMzhbMSYSOotqGyVPitYwLKYAMT3OId46WngGkHNBiq',
                'created_at' => '2021-11-11 08:36:38',
                'updated_at' => '2023-02-03 11:23:03',
            ),
            2 => 
            array (
                'id' => 4,
                'name' => 'rougou-nkombegnindault-pierrold',
                'email' => 'p.rougou@sgs-gabon.com',
                'phone_number' => 'null',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-07-04 10:38:25',
                'password' => '$2y$10$k0RvRg4gW0fiZFjaqz4wgun825b5p/HZayQB0QeTymUajuGqNFLM2',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-11-11 08:36:38',
                'updated_at' => '2022-07-04 10:38:25',
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'yao-ekra-epouse-embinga-sonia-carole',
                'email' => 'rh.pog@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-14 09:04:36',
                'password' => '$2y$10$r6dc6xPJnELXEYY0fpBEo.Ir2M1gwZW2aH7Vj9jsS2gzY6yUurS4G',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-12-12 20:21:42',
                'updated_at' => '2021-12-14 09:04:36',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'dev-gtech',
                'email' => 'dev@gabontech.com',
                'phone_number' => NULL,
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => NULL,
                'password' => '$2y$10$shsDbf8NauPn3XmzzprBuuTnFeerlTftis2DXLcR9bxS6OTJQZUd2',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'BsvYj4aAy5SOIqq9SlrYAeIDFCP9K33QxjfZUts04MW2bdEI5SStJhoyGTZJ',
                'created_at' => '2021-12-13 08:37:23',
                'updated_at' => '2023-01-20 10:19:01',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'ekome-assengone-fredy',
                'email' => 'f.ekomeassengone@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-14 09:04:46',
                'password' => '$2y$10$kJpJaUtM4dVfGdGzfYBZneMYFQirhKSU9zog/Cjzip3F38NsqLGIO',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-12-13 12:12:57',
                'updated_at' => '2021-12-14 09:04:46',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'kamatcho-melodie',
                'email' => 'm.kamatcho@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-14 09:04:57',
                'password' => '$2y$10$n2SjdASIbRMbnSbcJS7ADe4e8KB60jDPsB2Lq933YjF28iNkU61Py',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'DSQGjxdOryHMfCkgrWP4w2nqKntPsSycBGH6wNG4OLUbJ2v9X2RL1NmlaM0y',
                'created_at' => '2021-12-13 12:14:37',
                'updated_at' => '2021-12-14 09:04:57',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'dieudonnenguema',
                'email' => 'dieudonne.nguema@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-15 08:13:19',
                'password' => '$2y$10$uRiY2HjRrzrLiic371FruODmG0xv2FQBjWB8i8v2ux9himul2A.5G',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-12-15 08:13:19',
                'updated_at' => '2021-12-15 08:13:19',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'melvinabessolo',
                'email' => 'melvin.abessolo@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-15 08:13:50',
                'password' => '$2y$10$qIC4U8tlUd.7IRPOLPDiEufGojKL94xjdS8xkBgsBDqqd97SSmj6e',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-12-15 08:13:50',
                'updated_at' => '2021-12-15 08:13:50',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'beyelendong',
                'email' => 'b.eyelendong@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-15 08:14:13',
                'password' => '$2y$10$/LvrGtejIT0NkirsuJD/2OUeYkgExRx/c7KEr4k.5TbfN3i5tpteu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-12-15 08:14:13',
                'updated_at' => '2021-12-15 08:14:13',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'b-diyombi',
                'email' => 'b.diyombi@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'photos/b_diyombi_YuCY112.jpg',
                'email_verified_at' => '2021-12-20 07:54:30',
                'password' => '$2y$10$/UMrc2phOE0Dmm39LwNH1.ogy9Sp0MWqFCOsdpMRcdha0Tl6oruta',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'xXuMeE2iuHJ6RI0QTS2irAlWPUbawsajifgA1A895UtS50pelDIdQtIGo9qi',
                'created_at' => '2021-12-20 07:54:30',
                'updated_at' => '2022-01-05 13:18:40',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'juste-emmanuel-mikala-mikala',
                'email' => 'Mikalajuste@gmail.com',
                'phone_number' => '+241 077153183',
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-26 21:51:41',
                'password' => '$2y$10$lhhQ1hlOOro34mSI7gWHyuh2oJIVrYUW5HRXDRxMfUu4dRRwmXy06',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'Po31pvfOr3g3ROjYl8ZHUvuPHPIK17ZetCSSzyKWrFU1y9bij6bKmspNQJRR',
                'created_at' => '2021-12-26 21:51:41',
                'updated_at' => '2022-08-08 09:52:56',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'gino-lequy',
                'email' => 'gino.lequy.sgs@gmail.com',
                'phone_number' => NULL,
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-30 07:15:39',
                'password' => '$2y$10$GN/cS6sjvLzIJk1lgVfR6OXDtmS7htl4pGKKrv7Po589W96yHzcRq',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'iHoZedFHTBQ0EDQSyBNXhgfxzetunhgne7yCklGMrz60RtijAoTi6KbFzrSf',
                'created_at' => '2021-12-30 07:15:39',
                'updated_at' => '2022-05-10 11:15:35',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'jb-mayombo',
                'email' => 'jb.mayombo@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2021-12-31 11:28:45',
                'password' => '$2y$10$IP33j5hZhOKTK/pfsSGpGu5oa8tDTjwWmcNnL61JRpjnKzX85L24i',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '8QhA8vz2QLNZ3bU0dlKuRJuUHpygpdJwogYCCpJWKfLbrjMUXrHvEdNdkSWb',
                'created_at' => '2021-12-31 11:28:45',
                'updated_at' => '2021-12-31 11:28:45',
            ),
            14 => 
            array (
                'id' => 18,
                'name' => 'essangabela-odounga-wilfrid',
                'email' => 'w.essangabela@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:26:49',
                'password' => '$2y$10$K9ho185dA/777tbsFTqJvOkXzFWOetWkvrdJ0RPDRQtU2ldqBarKS',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:26:49',
                'updated_at' => '2022-01-06 14:03:31',
            ),
            15 => 
            array (
                'id' => 19,
                'name' => 'prisca-ngounda',
                'email' => 'prisca.ngounda@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:27:22',
                'password' => '$2y$10$f3PCeWU3.SzYl3J/DFUFS.av4xcnFOBSKYRnSDWDZbISqODd7S5XK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:27:22',
                'updated_at' => '2022-01-05 10:33:59',
            ),
            16 => 
            array (
                'id' => 20,
                'name' => 'diane-makaba',
                'email' => 'diane.makaba@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:27:47',
                'password' => '$2y$10$fwz4D5MARVfx9OLWw35wAeakntZ9M/wnUWVhqWYBnbBZ8VHrRNVYS',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:27:47',
                'updated_at' => '2022-01-06 12:59:45',
            ),
            17 => 
            array (
                'id' => 21,
                'name' => 'be-ndong-armand-davy',
                'email' => 'ad.bendong@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:28:13',
                'password' => '$2y$10$K7UbvUj3sbejnGj9WZLXYe1eOJcUTnXQg9vwPiP0hgpoNXOskjHIi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:28:13',
                'updated_at' => '2022-01-06 14:29:53',
            ),
            18 => 
            array (
                'id' => 22,
                'name' => 'eric-mabika',
                'email' => 'eric.mabika@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:28:43',
                'password' => '$2y$10$aTA/AYasevhJcxblilsZSOBin1vLgRqQxsPMz/z/5.s6m.tPq4Cd2',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:28:43',
                'updated_at' => '2022-01-06 13:49:30',
            ),
            19 => 
            array (
                'id' => 23,
                'name' => 'mbang-tsimis-hegue-zelle',
                'email' => 'hz.mbangtsimis@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-04-06 08:00:46',
                'password' => '$2y$10$iH7oy0ERDkVsUph/upGboOJw7wDcxwd0xvx5um.XfgHtIquConPg6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'vkIg4VLhgzKLCyd1Us7dvrrCghm8kPoGNprrVTFeme5j8cXUgCZ1kOB2XA4L',
                'created_at' => '2022-01-05 07:29:06',
                'updated_at' => '2022-04-06 08:00:46',
            ),
            20 => 
            array (
                'id' => 24,
                'name' => 'eric-nguemandong',
                'email' => 'eric.nguemandong@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:29:51',
                'password' => '$2y$10$.waJ3fxty1ufpx/zxUOzyu4yb2pYHNlcqRYG2xCWHBxFIV4Tj4RwG',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:29:51',
                'updated_at' => '2022-01-05 07:31:00',
            ),
            21 => 
            array (
                'id' => 25,
                'name' => 'christian-ndiama',
                'email' => 'christian.ndiama@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-05 07:30:17',
                'password' => '$2y$10$7dL0x1byTqhfS.doJnmx7eoTS/.0I8ABgiGinJQMVhx1DgUgVN0lm',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-05 07:30:17',
                'updated_at' => '2022-01-05 07:30:43',
            ),
            22 => 
            array (
                'id' => 26,
                'name' => 'opela-boris',
                'email' => 'boris.opela@sgs-gabon.com',
                'phone_number' => '077777701',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-06 08:22:01',
                'password' => '$2y$10$em.zh5QG0xNxIePdu5F4IO8rkXGlZgWjj7joatESC1hkBdg82wCcO',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-06 08:22:01',
                'updated_at' => '2022-01-06 08:44:35',
            ),
            23 => 
            array (
                'id' => 27,
                'name' => 'mpaki-ewing-alexis',
                'email' => 'alexis.mpaki@sgs-gabon.com',
                'phone_number' => '077777701',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-06 08:48:10',
                'password' => '$2y$10$yMmzi8ysP4n5vMrhyGeTYOpTJ1T56tQRKBIV2mXxb.GNOKWlKQdPu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-01-06 08:23:02',
                'updated_at' => '2022-01-06 08:50:53',
            ),
            24 => 
            array (
                'id' => 28,
                'name' => 'grace-sandrel-mbonzi',
                'email' => 'g.mbonzi@sgs-gabon.com',
                'phone_number' => '0777288037',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-11 16:16:38',
                'password' => '$2y$10$IjmscjZ2eUD5oGJmwiGwv.DNYjQ86zLXeIIUco2UVXreaBTwqGtKu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '3YHYTVRxxDqtgFLj2gQi6Dxorlba35PlOFLQCkszVVZ2IViw9dkAKe3mNcNb',
                'created_at' => '2022-01-11 16:16:38',
                'updated_at' => '2022-01-11 16:27:04',
            ),
            25 => 
            array (
                'id' => 29,
                'name' => 'ngnindong-mba-emmanuelle',
                'email' => 'e.ngnindong@sgs-gabon.com',
                'phone_number' => '0777288037',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-11 16:18:16',
                'password' => '$2y$10$5Z6VW.gp0nNAkPecO8uWB..kwTaquwwQBn0L34JKFdXPfzeCOyM4K',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'TRFbF8k55tCHqBfvOt5ErFgenhyEWKu71SX3vMc3eoi2RbGc2srpf3pustUj',
                'created_at' => '2022-01-11 16:18:16',
                'updated_at' => '2022-01-11 16:31:48',
            ),
            26 => 
            array (
                'id' => 30,
                'name' => 'vangou-alevinat',
                'email' => 'a.vangou@sgs-gabon.com',
                'phone_number' => '0777288037',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-01-11 16:19:41',
                'password' => '$2y$10$B8LRasjlLtW91jTz4nixDOwWZ.OhVgEYKMmC6RteUF3i7vMB3xx2C',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'p5H8iE0zukv8LYWhFcjbqRQ62KcfnL864xwMv9f34j1EzE6zKAJ7JtyaslGs',
                'created_at' => '2022-01-11 16:19:41',
                'updated_at' => '2022-05-10 07:43:36',
            ),
            27 => 
            array (
                'id' => 32,
                'name' => 'mboumba-boukoumou-eurydice',
                'email' => 'e.mboumba@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 1,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-02-10 11:39:47',
                'password' => '$2y$10$HC4owbOH39Qa7Irsnrqp1uwl4gwuyoZvyHoAeap5aiGdpEOx/rzPu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'ndQVbyaZrr53Xx9CCE2SgupB7vfk0eaR7Ta9YFdvw5KARmcGSvP5lELm6hQ7',
                'created_at' => '2022-02-10 11:39:47',
                'updated_at' => '2022-02-11 12:19:50',
            ),
            28 => 
            array (
                'id' => 33,
                'name' => 'schneider-christophe',
                'email' => 'c.schneider@sgs-gabon.com',
                'phone_number' => NULL,
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-02-10 11:40:25',
                'password' => '$2y$10$4XjL2WsjA6bwJks7I0gn8etrdEYcFPMd7BSuGE4ROWKqfnFCvpPjK',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-02-10 11:40:25',
                'updated_at' => '2022-02-10 11:40:25',
            ),
            29 => 
            array (
                'id' => 37,
                'name' => 'faustin-obounda',
                'email' => 'f.obounda@sgs-gabon.com',
                'phone_number' => '0777288037',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-05-03 11:32:54',
                'password' => '$2y$10$uTf6EJMz9yMzsZ4HmGikGOGLIH58s.u5UAdx7QolAg3QMPlDvhFU6',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-05-03 11:32:54',
                'updated_at' => '2022-05-03 11:32:54',
            ),
            30 => 
            array (
                'id' => 42,
                'name' => 'fobounda',
                'email' => 'fobounda@gmail.com',
                'phone_number' => '077930393',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-05-04 10:49:54',
                'password' => '$2y$10$1/bXdXESU7AzQHzz1V7FGe1H3bWQJfz4fHK441uoFqf/ypyRmON1W',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-05-04 10:49:54',
                'updated_at' => '2022-05-04 11:08:44',
            ),
            31 => 
            array (
                'id' => 43,
                'name' => 'gtech-flora',
                'email' => 'admin@gabontech.com',
                'phone_number' => '06554433',
                'is_admin' => 0,
                'is_online' => 0,
                'photo' => 'images/default_photo.jpg',
                'email_verified_at' => '2022-05-04 10:51:26',
                'password' => '$2y$10$mC1le4WbvH7i.qV1TZug3uN/VNoH/0LN9eZSYil1iVQlSuYG0y4nm',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-05-04 10:51:26',
                'updated_at' => '2022-05-04 10:51:26',
            ),
        ));
        
        
    }
}